services:
  # Backend API Service
  - type: web
    name: rendnitp-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 3000

  # Frontend Service
  - type: static
    name: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://backend-api.onrender.com 